### PR TITLE
Do not run crane's tests during provisioning.

### PR DESCRIPTION
**Pull request by rbarlow**

### CODE REVIEW

**Comment by rbarlow** [comment]
ok test

**Comment by dkliban** [comment]
ok test

**Comment by dkliban** [comment]
ok test

**Comment by rbarlow** [comment]
There's no way this PR has anything to do with RHEL 5, so I'm going to merge it anyway. Also, we know that the Jenkins environment is broken right now.

**Comment by dkliban** [comment]
ok test

**Pull request merged**
