### PR TITLE
Improved logging of worker abnormal termination.

### PR DESCRIPTION
**Pull request by jortel**
https://pulp.plan.io/issues/2551

### CODE REVIEW

**Comment by jortel** [comment]
Thanks for the review @bmbouter.  The jenkins test failure looks unrelated and is a failed import of nectar.listener.  Seems like a jenkins builder problem.  I don't see any flake8 failures but did spot a warning in the console output for a module unrelated to this PR:
```
16:15:47 ./streamer/pulp/streamer/server.py:240:39: W291 trailing whitespace
```
 Travis is happy.

Am I missing something?

**Comment by bmbouter** [comment]
@jortel Yes that trailing whitespace is causing the failures in Jenkins. I also thought it was a code problem until another dev who looked at the output noticed that single line was causing the failures.

**Comment by jortel** [comment]
ok test

**Comment by jortel** [comment]
flake8 warning fixed https://github.com/pulp/pulp/pull/2955

**Pull request merged**
