### PR TITLE
Use the hostname in crane.conf

### PR DESCRIPTION
**Pull request by rbarlow**
Quite hypocritically I hardcoded a hostname into our development environment. This is a commit of shame.

### CODE REVIEW

**Comment by jeremycline** [comment]
If you merge this, you'd best merge https://github.com/pulp/pulp/pull/2279 to hide my shame as well.

**Comment by rbarlow** [comment]
@jeremycline lol

**Comment by rbarlow** [comment]
ok test

**Comment by rbarlow** [comment]
ok test

**Comment by rbarlow** [comment]
I've filed an issue about this Jenkies failure: https://pulp.plan.io/issues/1615

I'm confident that it is not due to the code in this pull request.

**Pull request merged**
