### PR TITLE
Remove Vagrant setup from the platform.

### PR DESCRIPTION
**Pull request by jeremycline**
The Vagrant tools and scripts has been moved to the devel repository.
Check out pulp/devel, copy Vagrantfile.example to Vagrantfile, and carry
on as usual.

### CODE REVIEW

**Comment by seandst** [comment]
The dev setup guide needs to be updated to point to the new location:
http://docs.pulpproject.org/en/2.10/nightly/dev-guide/contributing/dev_setup.html#vagrant

**Comment by jeremycline** [comment]
Good point. Looking at the current state of the dev setup guide, there are quite a few things in need of updating. I think I'm going to make a separate PR that generally "refreshes" the guide and merge that prior to this PR.

**Comment by jeremycline** [comment]
Docs are updated here: https://github.com/pulp/pulp/pull/2645

**Comment by asmacdo** [comment]
Since this will be a breaking change in developer workflow, could you send an email heads up to the mailing list when you merge?

**Comment by jeremycline** [comment]
@asmacdo email sent!

**Pull request merged**
