### PR TITLE
Add usage of gprof2dot which can make profiling graphs

### PR DESCRIPTION
**Pull request by emilyzheng**

### CODE REVIEW

**Comment by dkliban** [comment]
Thanks for the contribution! I will test it and merge it if all works as you describe :)

**Comment by dkliban** [comment]
You should probably add that `graphviz` package should be installed using yum or dnf. When I installed using `pip`, the `dot` command was not available.

**Comment by emilyzheng** [comment]
Please check whether the modified description is clear.

**Comment by dkliban** [comment]
Thanks you for the contribution!

**Comment by bmbouter** [comment]
@emilyzheng Thank you very much for this!

**Comment by emilyzheng** [comment]
My pleasure!

**Pull request merged**
