### PR TITLE
fixes #2786: Allow content application to use console logging

### PR DESCRIPTION
**Pull request by ehelms**
I have not touched tests yet but I did include re-factoring to better centralize common validation checks of the configuration and required availability of things like the syslog path.

The context for the change is that I have created a stand alone container that runs Apache and serves up the content and repo_auth wsgi applications independent of having a Pulp server present.

### CODE REVIEW

**Comment by dkliban** [comment]
ok test

**Comment by bmbouter** [comment]
ok test

**Comment by mhrivnak** [comment]
ok test

**Comment by mhrivnak** [comment]
I added some polish and rebased this, which is available in this PR: https://github.com/pulp/pulp/pull/3095

We should probably get that merged, and then close this one.

**Comment by mhrivnak** [comment]
merged in https://github.com/pulp/pulp/pull/3095

Thanks @ehelms !

**Pull request closed without merging**
