### PR TITLE
PEP-8 pulp.plugins.util.

### PR DESCRIPTION
**Pull request by rbarlow**

### CODE REVIEW

**Comment by barnabycourt** [comment]
ok test

**Comment by asmacdo** [comment]
Assigning @rbarlow until conficts are resolved.  (So we don't keep checking this one for review.)

**Comment by rbarlow** [comment]
@asmacdo I don't think merge conflicts should be a reason to avoid review. The PEP-8 PRs will all conflict immediately when others are merged since they all edit the list of flake8 paths in run-tests.py. This means that every time I merge one, all the others will become conflicted. Thus, it's not scalable to require PRs to have the "OK to merge" button. I will resolve conflicts when I merge it by hand.

**Comment by asmacdo** [comment]
@rbarlow, fair point. LGTM

**Pull request merged**
