### PR TITLE
Configure the Vagrant box to use qxl/spice

### PR DESCRIPTION
**Pull request by rbarlow**
This commit adjusts the video in the guest to use Spice/QXL for
better performance.

### CODE REVIEW

**Comment by rbarlow** [comment]
@barnabycourt It looks like our Jenkins builder is upset because httpd didn't get installed on the F20 builder (the error message is that apachectl does not exist).

**Comment by rbarlow** [comment]
ok test

**Comment by rbarlow** [comment]
ok test

**Comment by rbarlow** [comment]
ok test

**Comment by rbarlow** [comment]
ok test

**Comment by rbarlow** [comment]
ok test

**Comment by rbarlow** [comment]
From IRC:

"""
13:24 <bowlofeggs> i still need review on this one that's been open for 6 weeks: https://github.com/pulp/pulp/pull/1921
13:29 <mhrivnak> bowlofeggs, it would probably help if you explain what it's doing. I suspect the problem is that nobody else understands it.
13:30 <mhrivnak> I guess your description basically explains it from a high level.
13:31 <mhrivnak> But I still feel unqualified to review it.
13:31 <bowlofeggs> mhrivnak: it really only changes the emulated "hardware" devices that the dev box gets configred with
13:32 <bowlofeggs> mhrivnak: it upgrades from cyrrus to qxl (much better graphics hardware) and then also upgrades the video protocol from VNC (remember the 90s?) to Spice (the cool new low bandwith one)
13:32 <bowlofeggs> and yeah, it's ruby - that code block is basically an anonymous function (think lambda) that gets handed to the libvirt function and run
13:33 <bowlofeggs> it gives us an opportunity to configure things about the vm itself, like ram, video, disk, etc.
13:33 <bowlofeggs> mhrivnak: does that help?
13:37 <mhrivnak> bowlofeggs, I'm in a meeting now, but I suggest adding that stuff to the PR description.
"""

**Comment by jeremycline** [comment]
:+1:
Let the spice flow.

**Comment by rbarlow** [comment]
On 07/31/2015 02:35 PM, Jeremy Cline wrote:
> Let the spice flow.

lol

**Pull request merged**
