### PR TITLE
Fixes Qpid file descriptor leak

### PR DESCRIPTION
**Pull request by bmbouter**
This fix is already in upstream Kombu so this ports
the important part of the fix to downstream

This commit bumps python-kombu to 3.0.33-6

https://pulp.plan.io/issues/2124
closes #2124

### CODE REVIEW

**Comment by seandst** [comment]
kombu's unit tests fail with this change when attempting a koji scratch build. I've sent more details to @bmbouter via email.

**Comment by bmbouter** [comment]
I will fix the unit tests. Thanks @seandst !

**Comment by bmbouter** [comment]
I pushed a new version which has fixed unit tests, but the hunk still doesn't apply correctly. I'll fix that next with another push.

**Comment by bmbouter** [comment]
I resolved the patch apply issue. Here is a completed scratch build.

http://koji.katello.org/koji/taskinfo?taskID=508896

**Comment by bmbouter** [comment]
non-scratch builds have been made for F23, EL6, and EL7 so this is now safe to merge.

**Pull request merged**
