### PR TITLE
Upgrade python-amqp dep to 1.4.9

### PR DESCRIPTION
**Pull request by pcreech**
Upgrade python-amqp dep to 1.4.9

### CODE REVIEW

**Comment by bmbouter** [comment]
@pcreech This all looks good, but how did the scratch builds go?

**Comment by bmbouter** [comment]
@pcreech oh and the real builds on koji.katello.org? Once the external_deps.json is merged the real builds need to be available. Can those be done pre-merge?

**Comment by pcreech** [comment]
@bmbouter scratch build success http://koji.katello.org/koji/taskinfo?taskID=416562

and wasn't sure when the real build needed to be available (i.e. pre merge or post merge).  Will do those real quick before merge

**Comment by bmbouter** [comment]
@pcreech great job

**Pull request merged**
