### PR TITLE
Removes ability to use password authentication when rsync-ing

### PR DESCRIPTION
**Pull request by dkliban**
re #1887
https://pulp.plan.io/issues/1887
re #1963
https://pulp.plan.io/issues/1963
re #1759
https://pulp.plan.io/issues/1759

### CODE REVIEW

**Comment by bmbouter** [comment]
@dkliban Should we remove `sshpass` as a dependency? I forget if its `sshpass` or not, but I remember there was some dependency that was added for this. Can that also be removed?

**Comment by dkliban** [comment]
We should!!!

**Comment by bmbouter** [comment]
@dkliban Thanks I see the change.

**Comment by bmbouter** [comment]
I did some hand testing and the configs validate as expected. Also some hand testing worked fine. There was one unrelated issue observed but we are handling that as a separate issue since it's unrelated to this PR.

**Comment by bmbouter** [comment]
@dkliban Also the test failure looks unrelated so I'm going to add the LGTM now.

**Pull request merged**
