### PR TITLE
Add an API for storing custom Unit metadata.

### PR DESCRIPTION
**Pull request by rbarlow**
https://pulp.plan.io/issues/86

closes #86

### CODE REVIEW

**Comment by rbarlow** [comment]
This very accurately describes what it was like to work on this story:

Working on Pulp

**Comment by mhrivnak** [comment]
I assume that when units are retrieved from requests such to URIs such as ``/pulp/api/v2/repositories/<repo_id>/search/units/``, the response will include this new field. It would be good to update those examples in the REST API docs to at least include the default value.

**Comment by mhrivnak** [comment]
LGTM

**Comment by rbarlow** [comment]
I've fixed the other documentation examples that involve units, thanks for noting that! I also filed a story to add some automation to test our documentation examples out so that it will be easier to find problems like this:

https://pulp.plan.io/issues/113

**Pull request merged**
