### PR TITLE
Add diagrams to Concepts and Terminology

### PR DESCRIPTION
**Pull request by pavelpicka**
Diagrams that illustrates all
of the concepts on the Concepts and Terminology page.

closes: #4100
https://pulp.plan.io/issues/4100

Signed-off-by: Pavel Picka <ppicka@redhat.com>

### CODE REVIEW

**Comment by bmbouter** [comment]
This is great because it will get the diagrams on the site which is important.

I had an idea I wanted to share from Pulp2. In pulp2's docs builder the source was checked into version control instead of the built png files. Then the docs builder would build the plantuml diagrams from the source with each docs build. This provides a few benefits:

1. It would keep the source in an area so it could be edited in the future
2. The images are always up to date after the source does change.

That code is here:  https://github.com/pulp/pulp/blob/2-master/docs/Makefile#L47-L50

I wanted to share the idea. It's not the smallest piece of work, so I'm really happy w/ this PR as is.

**Comment by pavelpicka** [comment]
This is a good idea, going to rewrite it to have the sources with our code.

**Comment by bmbouter** [comment]
@pavelpicka awesome! In the pulp2 code you can see sphinx including the images in their built location. Post here on the issue if you want me to find one specifically for you to see.

**Comment by pavelpicka** [comment]
Please share, I went through Makefile in pulp2 (https://github.com/pulp/pulp/blob/2-master/docs/Makefile#L47) and that is why I used it same way here.

**Comment by dralley** [comment]
@bmbouter @pavelpicka ping, is this PR currently complete?

**Comment by bmbouter** [comment]
It looks right to me, but it needs tessting. It would be great if someone else could see if the diagrams make correctly as part of the docs build and the sphinx links render them correctly.

**Comment by bmbouter** [comment]
Oh and I'll be out until Monday so +1 to continuing without me

**Pull request merged**
