### PR TITLE
Update last_unit_added when unit is imported to repo.

### PR DESCRIPTION
**Pull request by werwty**
closes #1847
https://pulp.plan.io/issues/1847

### CODE REVIEW

**Comment by daviddavis** [comment]
What about when syncing a repo? Does or should `last_unit_added` get updated?

**Comment by werwty** [comment]
ah you're right. I will update this PR. Thanks @daviddavis

**Comment by wiad** [comment]
Yes, it should get updated on sync, but only if the sync actually results in any updated units - right?

**Comment by daviddavis** [comment]
@wiad correct.

**Comment by werwty** [comment]
ok test

**Comment by wiad** [comment]
Should not 'last_unit_added' be updated when copying a rpm file from one repo to another? I'm running 2.12.0 and a `pulp-admin rpm repo copy rpm` does not modify the last_unit_added metadata, but a `pulp-admin rpm repo sync run` does.

**Comment by werwty** [comment]
@wiad it should be updated when copying. I missed that use case :(
Here is the new issue I filed for this: https://pulp.plan.io/issues/2577

**Pull request merged**
