### PR TITLE
Fix pulp-dev.py for CentOS 7.

### PR DESCRIPTION
**Pull request by rbarlow**

### CODE REVIEW

**Comment by beav** [comment]
ok test

**Comment by beav** [comment]
LGTM after build run passes. The previous run failed for reasons unrelated to this PR.

**Comment by rbarlow** [comment]
@beav I updated the pull request to calculate the LSB release a little bit differently that should work for all of these strings:

21
7.1
7.0.1402

Hopefully Jenkins will pass this one.

**Comment by rbarlow** [comment]
ok test

**Pull request merged**
