### PR TITLE
Add importer filters

### PR DESCRIPTION
**Pull request by daviddavis**
fixes #3080
https://pulp.plan.io/issues/3080

### CODE REVIEW

**Comment by daviddavis** [comment]
Note: the name param is added by ContentAdaptorFilter.

**Comment by asmacdo** [comment]
I thought we had decided not to do id_in_list anymore since the users won't really see the id. They would probably want to do href_in_list.

**Comment by asmacdo** [comment]
> Note: the name filter param is added by ContentAdaptorFilter.
repo_name?

**Comment by daviddavis** [comment]
I removed the id_in_list filter and opened [a href_in_list issue](https://pulp.plan.io/issues/3240) per our discussion on IRC.

**Pull request merged**
