### PR TITLE
Remove User REST api call.

### PR DESCRIPTION
**Pull request by ipanova**
closes #4398
https://pulp.plan.io/issues/4398

Please be sure you have read our documentation on creating PRs:
https://docs.pulpproject.org/en/3.0/nightly/contributing/pull-request-walkthrough.html

### CODE REVIEW

**Comment by bmbouter** [comment]
@pulp/qe Should this PR also remove the API tests for JWT and User auth?

**Comment by kersommoura** [comment]
Since USER endpoints were remove +1 to remove the tests as well.

**Comment by ipanova** [comment]
@kersommoura @bmbouter i was unsure who should remove the tests. since i got the ack i will remove them in this PR.

**Comment by bmbouter** [comment]
The changes look right, but there are two tests that are failing on Travis. Also it's saying it's hitting the 10-minute timeout limit too still.

**Comment by kersommoura** [comment]
@bmbouter, I checkout this branch locally, and I am running the tests. This time out issue has to be addressed, but I do not think this PR introduced it.

**Comment by kersommoura** [comment]
@ipanova, 

```shell
pulpcore/tests/functional/api/test_auth.py::AuthTestCase::test_base_auth_failure FAILED [  3%]
```


```python
class AuthTestCase(unittest.TestCase):
    """Test Pulp3 Authentication."""

    def setUp(self):
        """Set common variable."""
        self.cfg = config.get_config()

    def test_base_auth_success(self):
        """Perform HTTP basic authentication with valid credentials.

        Assert that a response indicating success is returned.

        Assertion is made by the response_handler.
        """
        api.Client(self.cfg, api.json_handler).get(
            USER_PATH,
            auth=HTTPBasicAuth(*self.cfg.pulp_auth),
        )
```

The auth tests are failing because they use the ``USER_PATH`` that was removed. We can modified this endpoint and add another that requires, user authentication in order to be accessed.

**Comment by kersommoura** [comment]
I will remove the [USER_PATH](
https://github.com/PulpQE/pulp-smash/blob/1d92c985a7f0c6fd71ca07812d93a1ee03223d17/pulp_smash/pulp3/constants.py#L39) from Pulp-Smash repo as well.

**Pull request merged**
