### PR TITLE
Add anonymous proxy support to client tools.

### PR DESCRIPTION
**Pull request by glbyers**
Story #3625 - As a user, I can use the CLI with an anonymous proxy

This is a rebasing of an old PR against 2-master (see https://github.com/pulp/pulp/pull/3395). 

Support for anonymous proxy in client tools. This filled a need in our organisation, and may be useful to others. Works in practice with pulp-consumer, pulp-admin and the goferd plugin.

### CODE REVIEW

**Comment by dralley** [comment]
Could you add the following to your commit message, rebase, and force-push?

```
Fixes: #3625
https://pulp.plan.io/issues/3625
```

Could you also add the release note from https://github.com/pulp/pulp/pull/3656/files, except under 2.19 notes?

**Comment by glbyers** [comment]
OK, I think I did that correctly. There was no pre-existing 2.19.x under release notes, so I've added it based on 2.18.x

**Comment by glbyers** [comment]
What do I need to do to get this in? This (and it's predecessor) have just sat here for over 12 months (combined) now, and each time there's an update I need to patch and rebuild the RPMs for our local install. 

Seems no one wants to give a yay or nay, although I was asked to add it to 2.19 release notes, which has since been released. With the last PR, I'd been asked to add it to 2.17 release notes, but that didn't eventuate either.

**Comment by dkliban** [comment]
@glbyers Thank you for the contribution. We would like to accept it. Let's rebase and plan for this to be in the 2.20 release. I apologize for forgetting about this PR. I

**Comment by glbyers** [comment]
Thank you @dkliban. 

Re-basing isn't part of my usual workflow, so I hope I have done this correctly. Certainly looks fine to me, but please let me know if there's anything else required. 

I also have a PR to raise against pulp_rpm that utilises this support (for the pulp-profile-update plugin), so i'll get that done too.

**Comment by dkliban** [comment]
ok test

**Comment by dkliban** [comment]
ok test

**Pull request merged**
