### PR TITLE
Node distributor removal now deletes published data.

### PR DESCRIPTION
**Pull request by mhrivnak**
re #681

https://pulp.plan.io/issues/681

### CODE REVIEW

**Comment by mhrivnak** [comment]
As a quick explanation, I did a small bit of re-arranging so that the publish dir for a given repo is only calculated in one place, which is now on the distributor's ``_get_publish_dir`` method.

**Comment by jortel** [comment]
LGTM

**Comment by jortel** [comment]
Since 2.6.0 has not been released.  shouldn't this go against 2.6-testing?

**Comment by mhrivnak** [comment]
I don't think it's worth delaying 2.6.0 for this. It can go in 2.6.1, and anyone who wants it sooner can cherry-pick it. I branched from 2.6-testing so it would cherry-pick cleanly.

**Pull request merged**
