### PR TITLE
Removes working directory cleanup from repo group delete

### PR DESCRIPTION
**Pull request by dkliban**
This is a fix for https://bugzilla.redhat.com/show_bug.cgi?id=1192177

### CODE REVIEW

**Comment by bmbouter** [comment]
@dkliban Where is the code that does the cleanup now?

**Comment by dkliban** [comment]
https://github.com/pulp/pulp/blob/master/server/pulp/server/async/tasks.py#L374
https://github.com/pulp/pulp/blob/master/server/pulp/server/async/tasks.py#L401

**Comment by bmbouter** [comment]
@dkliban cool. Is there another place where cleanup happens if neither of these handlers run?

**Comment by dkliban** [comment]
@bmbouter  https://github.com/pulp/pulp/blob/master/server/pulp/server/async/tasks.py#L126

**Comment by bmbouter** [comment]
Cool, the removing of the code is all we needed here. I don't think any new tests are needed since there this code is going to be rewritten with mongoengine in the not-too-distant future. LGTM.

**Pull request merged**
