### PR TITLE
Checking in migrations

### PR DESCRIPTION
**Pull request by daviddavis**
fixes #4067
https://pulp.plan.io/issues/4067

### CODE REVIEW

**Comment by daviddavis** [comment]
No idea why pep8speaks is raising errors for migrations. Should be ignored:

https://github.com/pulp/pulp/blob/master/.pep8speaks.yml#L8

**Comment by asmacdo** [comment]
@daviddavis could you also remove the lines from https://github.com/pulp/pulp/blob/master/docs/installation/instructions.rst that instruct users to make migrations?

**Comment by daviddavis** [comment]
@asmacdo am I just removing the makemigrations line?

**Comment by asmacdo** [comment]
daviddavis yeah remove makemigrations at a minimum, but if you wanted to pick up https://pulp.plan.io/issues/3062 you might be able to remove the `migrate --noinput auth` line too

**Pull request merged**
