### PR TITLE
Add twine, pkginfo, and setuptools to our external deps

### PR DESCRIPTION
**Pull request by jeremycline**
pulp-python-2.0 requires twine, which depends on pkginfo and setuptools
which are newer than those available in EL6. We must carry all three of
these dependencies until we drop EL6 or newer versions (see the twine
specfile for exact requirements) are available.

Note: I have not built these in Katello's Koji, as I do not have access.
I did build and install them locally, however, so they should build without
trouble.

### CODE REVIEW

**Comment by seandst** [comment]
Have these already been built in koji? I can help with that, if not.

**Comment by jeremycline** [comment]
They have not been built in Koji yet.

**Comment by seandst** [comment]
LGTM, but we'll need the koji builds done for el6

**Comment by seandst** [comment]
Wait, I lied. All the other external deps have the release component of the version. Do these need that?

**Comment by jeremycline** [comment]
Oh good catch. I assume they do, but I have absolutely no clue how external_deps.json is consumed :shipit:

**Comment by jeremycline** [comment]
I've updated external_deps.json with the releases.

**Comment by ipanova** [comment]
@jeremycline if you want to get the access here is some useful info whom you need to ping http://projects.theforeman.org/projects/foreman/wiki/Koji

**Comment by jeremycline** [comment]
To clarify, do I need to build this in Koji before merging, or after merging?

**Comment by ipanova** [comment]
@jeremycline i think this PR should be divided in 2, first would contain all the spec files what you would need to build the deps. Once the deps are build on koji you create and merge PR w/r to external_deps.json update.

**Comment by jeremycline** [comment]
I can just build the deps in Koji right now and merge it all in one go. Is there any reason to not do that?

**Comment by ipanova** [comment]
closing this Pr in favour of https://github.com/pulp/pulp/pull/2766

**Pull request closed without merging**
