### PR TITLE
Adds description of the date filters format

### PR DESCRIPTION
**Pull request by vdusek**
closes #3825
https://pulp.plan.io/issues/3825

### CODE REVIEW

**Comment by vdusek** [comment]
Fixed.

**Comment by dralley** [comment]
@daviddavis @dkliban Wouldn't it be better to add support for this [upstream](https://github.com/carltongibson/django-filter/blob/master/django_filters/filters.py#L272)?  

django-filters already has ```help_text``` for [some](https://github.com/carltongibson/django-filter/blob/master/django_filters/filters.py#L492) fields, just not all of them.

**Comment by daviddavis** [comment]
@dralley reading through the discussions upstream, it seemed like they weren't keen on it. In fact, this solution is based on what they proposed [here](https://github.com/carltongibson/django-filter/issues/754#issuecomment-321059424).

**Comment by daviddavis** [comment]
Actually, I think it would be a good idea to try to submit this upstream. 👍 from me.

**Comment by vdusek** [comment]
Ok, I opened PR on django-filters - https://github.com/carltongibson/django-filter/pull/961.

**Comment by daviddavis** [comment]
I'm going to wait a couple more days for a response on carltongibson/django-filter#961 and if there's none, I'll merge this.

**Comment by daviddavis** [comment]
No response from upstream. Merging.

**Pull request merged**
