### PR TITLE
Refactor 1148: Removing 'timed out' state from Pulp's task state list

### PR DESCRIPTION
**Pull request by shubham90**
https://pulp.plan.io/issues/1148

closes #1148

### CODE REVIEW

**Comment by ipanova** [comment]
@shubham90  we usually remove the copyright header in the PR in case we see it. https://github.com/shubham90/pulp/blob/i1148/common/pulp/common/constants.py#L3 you could also remove it.

**Comment by ipanova** [comment]
LGTM

**Comment by shubham90** [comment]
ok test

**Comment by shubham90** [comment]
ok test

**Comment by shubham90** [comment]
ok test

**Comment by shubham90** [comment]
ok test

**Pull request merged**
