### PR TITLE
2033 merge forward

### PR DESCRIPTION
**Pull request by asmacdo**
Since I this has been refactored in master, this change is going into a different file. 

Small change, but since it is a different file and an unit test changed, I thought it would be better to open a PR for this merge.

### CODE REVIEW

**Comment by dkliban** [comment]
LGTM once pulpbot gives it's blessing

**Comment by asmacdo** [comment]
Haiku:

unit tests fail
not my fault, cmon @pulpbot 
get it together

**Comment by asmacdo** [comment]
ok test

**Comment by rbarlow** [comment]
Austin wrote:
> Haiku:
> 
> unit tests fail
> not my fault, cmon @pulpbot <https://github.com/pulpbot>
> get it together

lol

**Pull request merged**
