### PR TITLE
Namespace DRF's ValidationError under serializers

### PR DESCRIPTION
**Pull request by daviddavis**
For more info see https://git.io/vAKBA

### CODE REVIEW

**Comment by daviddavis** [comment]
@ammaritiz good catch. updated.

**Comment by ammaritiz** [comment]
Please make the changes in this [file](https://github.com/pulp/pulp/blob/3.0-dev/pulpcore/pulpcore/app/serializers/fields.py) too.

**Comment by daviddavis** [comment]
Done.

**Comment by ammaritiz** [comment]
Please update the docstring [here.](https://github.com/pulp/pulp/blob/3.0-dev/pulpcore/pulpcore/app/serializers/fields.py#L54) Otherwise, LGTM 👍

**Comment by daviddavis** [comment]
I think the docstring is correct: [ValidationError is defined in the exceptions module](https://github.com/encode/django-rest-framework/blob/master/rest_framework/exceptions.py#L138).

**Comment by ammaritiz** [comment]
Agreed. But we need to be consistent. You have updated the docstring in the [base module.](https://github.com/pulp/pulp/pull/3343/files#diff-ae7f375b1b9eaee42aecdf250679cd6eR58)

**Comment by daviddavis** [comment]
Ah good catch. Do you think the docstring should point to `serializers` or `exceptions`? I've updated the PR to use the latter but let me know if you disagree.

**Pull request merged**
