### PR TITLE
Fix mongoengine

### PR DESCRIPTION
**Pull request by dkliban**
Had to add some pep8 fix on top of @bmbouter original PR.

### CODE REVIEW

**Comment by ipanova** [comment]
ok test

**Comment by dkliban** [comment]
ok test

**Comment by dkliban** [comment]
ok test

**Comment by dkliban** [comment]
ok test

**Comment by dkliban** [comment]
ok test

**Comment by dkliban** [comment]
ok test

**Comment by dkliban** [comment]
ok test

**Pull request merged**
