### PR TITLE
Fix fast forward mode for rsync publish.

### PR DESCRIPTION
**Pull request by ipanova**
closes #2666
https://pulp.plan.io/issues/2666

### CODE REVIEW

**Comment by ipanova** [comment]
```
1. create repo with 2 dist( yum and rsync)
2. add feed zoo
3. publish with rsync dist and check publish has skipped result
4. sync repo and publish with both dist
5. check 32 num of processed units with rsync dist
6. add 1 rpm
7. publish with both dist
8. check 1 num of processed units with rsync dist
9. publish with rsync and check publish has skipped result
10. publish with both dist
11. check 0 num of processed units with rsync dist
```
11 remove 1 rpm
12 publish with both
13 check 32 items proc
```

**Comment by dkliban** [comment]
ok test

**Comment by ipanova** [comment]
@Ichimonji10 i know that you already have some of the tests for rsync distributor, but please take a look at the steps i took to test this fix, maybe you can take some useful corner cases from here and expand the existing test suite.

**Comment by dkliban** [comment]
ok test

**Comment by dkliban** [comment]
ok test

**Comment by dkliban** [comment]
ok test

**Comment by dralley** [comment]
@ipanova, would you mind posting the commands you used to test this locally, if they are not identical to the ones in https://pulp.plan.io/issues/2666?

Unfortunately I am not yet very familiar with interacting with pulp via the API or CLI outside of basic tasks.

**Comment by ipanova** [comment]
@dralley http://pastebin.test.redhat.com/476499

other actions like update feed and trigger yum_dist publish can be done via cli

**Comment by dralley** [comment]
I was able to test this, and it seems as though it partially works, but I'm not sure it fully resolves the issue.

Here is the output I get from testing with the patch applied (the task info for the last task after yum publish -> rsync publish -> yum publish -> rsync publish)

```
Operations:       publish
Resources:        test-repo380 (repository)
State:            Successful
Start Time:       2017-05-01T18:09:47Z
Finish Time:      2017-05-01T18:09:47Z
Result:           
  Completed:           2017-05-01T18:09:47Z
  Details:             
    Description:   
    Details:       
    Error Details: 
    Items Total:   0
    Num Failures:  0
    Num Processed: 0
    Num Success:   0
    State:         FINISHED
    Step Id:       df7640e1-bb7e-48f9-b8b1-b70fab4e06f0
    Step Type:     Unit query step (rpm, drpm, srpm)
    Description:   Rsync files to remote destination
    Details:       
    Error Details: 
    Items Total:   1
    Num Failures:  0
    Num Processed: 1
    Num Success:   1
    State:         FINISHED
    Step Id:       e34f4bf7-9e1c-4d48-aa51-50fca60b16c0
    Step Type:     Rsync step (origin)
    Description:   Rsync files to remote destination
    Details:       
    Error Details: 
    Items Total:   1
    Num Failures:  0
    Num Processed: 1
    Num Success:   1
    State:         FINISHED
    Step Id:       9b4dec15-34c9-40cf-bfed-785e50a9e04a
    Step Type:     Rsync step (content)
    Description:   Rsync files to remote destination
    Details:       
    Error Details: 
    Items Total:   1
    Num Failures:  0
    Num Processed: 1
    Num Success:   1
    State:         FINISHED
    Step Id:       6f072ead-c080-49c2-b147-e8333e3e16c3
    Step Type:     Rsync step (repodata)
  Distributor Id:      my_rpm_rsync_distributor
  Distributor Type Id: rpm_rsync_distributor
  Error Message:       None
  Exception:           None
  Id:                  590779eb0142ed14ef3a6321
  Repo Id:             test-repo380
  Result:              success
  Started:             2017-05-01T18:09:47Z
  Summary:             
    Rsync step (content):              FINISHED
    Rsync step (origin):               FINISHED
    Rsync step (repodata):             FINISHED
    Unit query step (rpm, drpm, srpm): FINISHED
  Traceback:           None
Task Id:          5c13e721-b6e7-4fea-989c-16f87606f0e3
```
Unless I'm reading this wrong, it looks like the rsync steps are still being executed.

**Comment by dralley** [comment]
LGTM @ipanova

**Pull request merged**
