### PR TITLE
Fix: 758.  Ensure gofer connector is added.

### PR DESCRIPTION
**Pull request by jortel**
https://pulp.plan.io/issues/758

Ensures that the gofer lib connector is configured before each RMI call.

Minor changes to the agent queue delete task to support query and cancel of this task when things go wrong.  Currently, no way to cancel the task.

Other minor changes to be consistent with contemporary gofer API.

### CODE REVIEW

**Comment by jortel** [comment]
ok test

**Comment by jortel** [comment]
ok test

**Comment by jortel** [comment]
ok test

**Comment by barnabycourt** [comment]
ok test

**Comment by jortel** [comment]
Reissue against 2.6-testing.

**Pull request closed without merging**
