### PR TITLE
Fixes #2776: Don't check for active works in dry-run

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by werwty** [comment]
@ehelms Since this is a bugfix could you rebase this PR onto the 2.13-dev branch?
The code looks good, but could you update the commit message to include `closes #2776` so [redmine can associate it correctly.](http://docs.pulpproject.org/dev-guide/contributing/branching.html#commit-messages)

**Comment by ehelms** [comment]
@werwty Sorry, I don't exactly follow the request. You are wanting me to?

  1) Put my commit onto the 2.13-dev branch
  2) Re-open my PR against the 2.13-branch

Also confused about the commit message change request. The document you linked to includes using the format I used here.

**Comment by werwty** [comment]
Github allows you to [change the target of the pull request ](https://github.com/blog/2224-change-the-base-branch-of-a-pull-request). This PR should target 2.13-dev.

I've always put the redmine reference in a separate line than the rest of the commit message. But looking at the [docs](http://www.redmine.org/projects/redmine/wiki/RedmineSettings#Referencing-issues-in-commit-messages), the way you have it should be fine :flushed: So please disregard that request and carry on

**Comment by ehelms** [comment]
@werwty Rebased and PR updated to point at 2.13-dev branch.

**Pull request merged**
