### PR TITLE
Reorganized the 3.0 dev branch

### PR DESCRIPTION
**Pull request by dralley**
Renames the 'app' top-level directory to 'platform'.
Consolidates several setup.py files. Moves several
top-level directories into the 'platform' directory
to better reflect the structure after installation.

closes #2463
https://pulp.plan.io/issues/2463

### CODE REVIEW

**Comment by dralley** [comment]
Associated pulp/devel PR:
https://github.com/pulp/devel/pull/49

**Comment by dralley** [comment]
ok test

**Comment by bmbouter** [comment]
@dralley I haven't tried yet, but does vagrant up work with this PR when run with pulp/devel#49?

**Comment by dralley** [comment]
@bmbouter You do need both, yes.  They should be reviewed together.

**Comment by bmbouter** [comment]
I'm testing the vagrant up now...

**Comment by bmbouter** [comment]
Vagrant up worked for me now let me use the environment some.

**Comment by bmbouter** [comment]
The code review all looks right. So does the state of the repo on your branch. I'm going to finish with some hand testing now.

**Pull request merged**
