### PR TITLE
Allow users to override page size

### PR DESCRIPTION
**Pull request by daviddavis**
fixes #3790
https://pulp.plan.io/issues/3790

Note: This is up for discussion on pulp-dev. Recommend waiting a bit before merging.

### CODE REVIEW

**Comment by dralley** [comment]
Looks good.  Should we set a max page size?

**Comment by daviddavis** [comment]
Sure, any thoughts on a good number?

**Comment by dralley** [comment]
5000 maybe?  I don't know what the guidelines are for determining that sort of thing.  And maybe we don't need one.

**Comment by daviddavis** [comment]
5000 sounds good to me. @jlsherrill does that meet your requirements?

**Comment by jlsherrill** [comment]
Yeah 5,000 is fine, we usually do it much lower in pulp 2, in the hundreds.  For pulp 3 i imagine we'll do some tests to try to optimize it to some degree.

**Pull request merged**
