### PR TITLE
Updated epel.rpm link, please note this will keep getting outdated as ep...

### PR DESCRIPTION
**Pull request by Jmainguy**
...el link will keep changing

### CODE REVIEW

**Comment by barnabycourt** [comment]
Is there a clean way to document this that will not keep getting outdated?

**Comment by Jmainguy** [comment]
We could provide a static epel rpm (Version does not really matter, older versions will just update when they yum update anyways)

We could try and get fedora to start using a static link which always post to their latest rpm. (Would be really helpful if they did this)

We could point users to go to this page 
http://download-i2.fedoraproject.org/pub/epel/7/x86_64/repoview/epel-release.html
And then tell them to rpm -Uvh the latest rpm on that page 

We could write a long string which curls the page, greps for rpm, returns the rpm, and have rpm -Uvh run against it, probably prone to error and not the best idea.

Of those options to any seem attractive to y'all, or y'all have any better ideas?

**Comment by beav** [comment]
I'd be :+1: for "provide static epel version and let it get updated via yum update"

**Comment by dkliban** [comment]
I didn't realize that this pull request existed.  I submitted my own yesterday with a note on how to find out the proper version.  It got merged yesterday.  https://github.com/pulp/pulp/pull/1621

**Pull request closed without merging**
