### PR TITLE
Bump patch version in dev branch

### PR DESCRIPTION
**Pull request by barnabycourt**

### CODE REVIEW

**Comment by beav** [comment]
is the `1a1` needed? [PEP-396](https://www.python.org/dev/peps/pep-0396/) just mentions x.y.z versions, maybe we can just do that to save some updates.

**Comment by barnabycourt** [comment]
ok test

**Comment by barnabycourt** [comment]
@beav This follows the StrictVersion from [PEP-0386](https://www.python.org/dev/peps/pep-0386/).  If we only specify x.y.z how do we know that something is from an alpha or beta build?

**Comment by beav** [comment]
Ah, I was not able to find that PEP in my orignial search :koala:

This change LGTM personally but @rbarlow had comments in other PRs that were related to this one. Maybe we should discuss this after scrum?

**Pull request merged**
