### PR TITLE
split database query in publish_step into multiple smaller ones

### PR DESCRIPTION
**Pull request by aschieb**
For large numbers of available packages this step breaks with an assertion in mongodb (assertion 13385 combinatorial limit of $in partitioning of result set exceeded).
I fixed it with running the database query multiple times for smaller subsets of our available units.

### CODE REVIEW

**Comment by beav** [comment]
Thanks for the pull request!

Could the paginate functionality in `pulp.plugins.util.misc` be used here?

**Comment by aschieb** [comment]
Yes, the paginate functionality could be used.
I changed my implementation to use this functionality.

**Comment by barnabycourt** [comment]
ok to test

**Comment by barnabycourt** [comment]
ok test

**Comment by beav** [comment]
ok test

**Comment by barnabycourt** [comment]
test this please

**Comment by barnabycourt** [comment]
ok to test

**Comment by barnabycourt** [comment]
ok to test

**Comment by barnabycourt** [comment]
@aschieb Looks like there is a unit test error, I'm not sure if all it might need is a rebase

**Comment by aschieb** [comment]
@barnabycourt I looked at this unit test and in my opinion it does not make sense.
I tests whether "get_multiple_units_by_keys_dicts" is called with no key dicts passed, which obvious could not return anything.

**Comment by beav** [comment]
ok test

**Comment by beav** [comment]
@aschieb I updated the tests for this but I'm not able to update this PR directly. I created a new one at https://github.com/pulp/pulp/pull/1707. The PR is in my name but the commit itself has you as the author so the git log will be correct.

I am going to close this PR since it's being tracked in #1707 . Thanks again for this patch!

**Pull request closed without merging**
