### PR TITLE
Remove the requestor's IP address from the signature.

### PR DESCRIPTION
**Pull request by jeremycline**
I encountered problems with this because one request was being made via
IPv6 and a second request was being made via IPv4.

### CODE REVIEW

**Comment by jeremycline** [comment]
ok test

**Comment by dkliban** [comment]
ok test

**Comment by dkliban** [comment]
This looks good to me. However, I am concerned that we are removing the IP address. The consequence is that the redirect URL can be used by anyone that sniffs HTTP traffic.

**Comment by jeremycline** [comment]
So I've given this some thought. It's unlikely that someone would run into the issue I ran into in the real world, but it could happen. If, for example, you make your request to http://192.168.1.100/repo/some.rpm and then get redirected to http://hostname/content/path/with/signature/ where hostname resolves to an IPv6 address, you will receive a 403.

I'm on the fence about whether or not we should merge this.

**Comment by jeremycline** [comment]
After some discussion it was decided that it would be best to just add some notes to the documentation on how to avoid this problem.

**Pull request closed without merging**
