### PR TITLE
1168331 - Give index pages useful sidebars.

### PR DESCRIPTION
**Pull request by rbarlow**
https://bugzilla.redhat.com/show_bug.cgi?id=1168331

### CODE REVIEW

**Comment by asmacdo** [comment]
@rbarlow, unfortunately, I think that this change only affects the default sphinx theme, not the sphinx_rtd_theme that read the docs uses.

**Comment by rbarlow** [comment]
On 01/08/2015 04:52 PM, Austin wrote:
> @rbarlow <https://github.com/rbarlow>, unfortunately, I think that this
> change only affects the default sphinx theme, not the sphinx_rtd_theme
> that read the docs uses.

Perhaps it is possible for us to get that RTD theme in our conf.py so
that WYSIWYG.

**Comment by asmacdo** [comment]
@rbarlow, I actually made that change, but it is only in master ATM.

**Comment by rbarlow** [comment]
@asmacdo I installed the theme (via yum in F20!) and it looks like you are correct ☹.

**Pull request closed without merging**
