### PR TITLE
pulp-server depends on pulp-selinux.

### PR DESCRIPTION
**Pull request by rbarlow**
https://pulp.plan.io/issues/1712

fixes #1712

### CODE REVIEW

**Comment by bmbouter** [comment]
Nice verified commit signature

**Comment by bmbouter** [comment]
:closed_lock_with_key:

**Comment by rbarlow** [comment]
Yeah! GPG sign everything!

**Comment by rbarlow** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

I mean, yeah! GPG sign everything!
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1

iQIcBAEBAgAGBQJXTw33AAoJEIyFaKUJtmpi8Z0P/Rdx2u92ERadpCCfo2qvm/Qw
xu6VfSEm2/p4ug0KzU0XM1WtZEopkBWI1KeqktApLvX4Phg3c+dnU+2wUrrqgvRF
rIRCrMgh7kA5zAh3Ntyi36v3Ah5F7h3/yxe8t99/9rb1f2eTdEPuHe1qjUPZ8vPG
Qqc8i/YnXSE/CupA18XfE3+CmoT2R0fAY5P1TozCrie4CBlT+P1dBdfyKlzcvZRu
GqE8bI1puySD2mcQO7yj9DdQQoq9eRGq9H0qavCS3RzPwkKbqm8YdcUpo021eYIO
zY4LjGMjP60Wx6uNn7Uz6Y5zeMcy66Y+cuctND2N4opzrlzeC3Ih6vw3pg/9Pa4G
gUQcswYqzQHKjvlWtKZMbedmO87LV55yJGvFiKvrRZwE+V4NSLSOavWsNCUj9rqZ
YZZHqe3LOmHyT5Esy2EktQ8m6RBn4hBY0oDRlDHQe7krSV3wz7GpSwfBUw0AFbPE
YE9gKoMH/ma3RiDc3lS1Pp/sb2qPe9gktr99IwbXsH6XLHHACOJqDxHjn8M0Zih/
J9ScW6hPTbBUVSHNTpYRaL24TfBjOFmA9KKN13avwNc4uPCO/x8CjlSf7yucoWPr
gn8u1DiKgVUli1Ja3xIrZ4PgNaDAeZxfTXIoVtS8w/0aJM3kHMyC3PLErumViT6O
1nBAkVG5KMTyVkAvtxz/
=0uJm
-----END PGP SIGNATURE-----

**Comment by bmbouter** [comment]
Hahaha, yes!

**Pull request merged**
