### PR TITLE
Add --keep-links option to rsync distributor

### PR DESCRIPTION
**Pull request by BrnoPCmaniak**
closes #2687
https://pulp.plan.io/issues/2687

### CODE REVIEW

**Comment by BrnoPCmaniak** [comment]
ok test

**Comment by dralley** [comment]
Since this is an issue targeted against 2.12 (according to Redmine), this PR should be made against 2.12-dev.

**Comment by dralley** [comment]
I think the commit message could also be less ambiguous - maybe say

```
Use rsync --keep-links option to preserve symlinks on publish
with rsync distributor
```

**Comment by BrnoPCmaniak** [comment]
closing will reopen against 2.12-dev

**Pull request closed without merging**
