### PR TITLE
API call to install consumers raises 500 if body contains wrong data type

### PR DESCRIPTION
**Pull request by eslynunez**
[Issue 1606](https://pulp.plan.io/issues/1606) Raise a 400 error if units are not a list of dictionaries

### CODE REVIEW

**Comment by asmacdo** [comment]
ok test

**Comment by asmacdo** [comment]
@eslynunez could you amend the commit include `closes #1606`? We have a bot that integrates with redmine that depends on that syntax. http://docs.pulpproject.org/dev-guide/contributing/merging.html#pull-requests

**Comment by eslynunez** [comment]
Commit amened. I'm guessing there's no problem referencing a github issue?

**Comment by asmacdo** [comment]
Thanks @eslynunez!!

**Comment by eslynunez** [comment]
Woohoo thanks!

**Pull request merged**
