### PR TITLE
Adding temporary fix for task state discrepancies.

### PR DESCRIPTION
**Pull request by ipanova**
closes #851
https://pulp.plan.io/issues/851

### CODE REVIEW

**Comment by dkliban** [comment]
ok test

**Comment by ipanova** [comment]
ok test

**Comment by ipanova** [comment]
ok test

**Comment by dkliban** [comment]
I had to rebase against the lastest 2.7-testing branch to get this working. I'd recommend rebasing against 2.7-testing and then you can merge. LGTM.

**Comment by ipanova** [comment]
ok test

**Pull request merged**
