### PR TITLE
serializer should not fail if masked or removed field is None

### PR DESCRIPTION
**Pull request by asmacdo**
https://pulp.plan.io/issues/1384

### CODE REVIEW

**Comment by dkliban** [comment]
ok test

**Comment by dkliban** [comment]
ok test

**Comment by dkliban** [comment]
ok test

**Comment by dkliban** [comment]
ok test

**Comment by dkliban** [comment]
ok test

**Comment by asmacdo** [comment]
ok test

**Comment by rbarlow** [comment]
LGTM, since the F23 builder is broken anyway.

**Comment by dkliban** [comment]
ok test

**Pull request merged**
