### PR TITLE
support vhost element of AMQP URI scheme

### PR DESCRIPTION
**Pull request by elho**
The AMQP URI scheme supports what it calls a "vhost" element, which basically just is an additinoal path element after the host/port elements, e.g. amqp://user@example.org:5672/vhost1?foo. Also see https://www.rabbitmq.com/uri-spec.html.

This change adds support for handling such AMQP URIs that contain a vhost element specified in the configuration.

### CODE REVIEW

**Comment by fonk** [comment]
I'm using this patch in our environment and it's working!

**Comment by jortel** [comment]
Thanks for the patch!  Please add *vhost* to the client_consumer/etc/pulp/consumer/consumer.conf [messaging] section documentation and commented out property.

**Comment by elho** [comment]
Done.

**Comment by jortel** [comment]
ok test

**Comment by barnabycourt** [comment]
flake8 error:
17:37:17 Running flake8
17:37:18 agent/pulp/agent/gofer/pulpplugin.py:121:101: E501 line too long (111 > 100 characters)

**Comment by elho** [comment]
Fixed the too long line.

**Comment by jortel** [comment]
ok test

**Pull request merged**
