### PR TITLE
PEP-8 tests for pulp.plugins.

### PR DESCRIPTION
**Pull request by rbarlow**

### CODE REVIEW

**Comment by asmacdo** [comment]
I got a few flake8 errors.

    working with fileserver/test/unit/plugins/file/test_distributor.py
    stdin:72:10: E111 indentation is not a multiple of four
    stdin:72:10: E113 unexpected indentation
    stdin:141:9: E265 block comment should start with '# '

    working with fileserver/test/unit/plugins/util/test_publish_step.py
    stdin:341:9: E265 block comment should start with '# '

**Comment by rbarlow** [comment]
On 01/26/2015 08:01 AM, Austin wrote:
> I got a few flake8 errors.
> 
> |working with fileserver/test/unit/plugins/file/test_distributor.py
> stdin:72:10: E111 indentation is not a multiple of four
> stdin:72:10: E113 unexpected indentation
> stdin:141:9: E265 block comment should start with '# '
> 
> working with fileserver/test/unit/plugins/util/test_publish_step.py
> stdin:341:9: E265 block comment should start with '# '
> |

I wonder why our two versions of flake8 do not seem to agree about these
problems. On my dev box, flake8 finds no issues with these files. This
is the second time this has happened. It does appear that my dev box has
the same version of flake8 as appears in F20 (2.0-5).

**Comment by rbarlow** [comment]
Even when I pip install --upgrade flake8 to 2.3, it still does not find these problems on my dev box. Another F20 dev box I have does see these issues. I wonder if it is a difference in a dependency.

**Comment by rbarlow** [comment]
The output you cited does not appear to be printed in the format usually provided by flake8. Are you actually using flake8 to test this? flake8 failures

**Comment by rbarlow** [comment]
@asmacdo I have fixed these errors, can you recheck?

**Comment by asmacdo** [comment]
@rbarlow, LGTM

I am using my tool https://github.com/asmacdo/pr8 to run flake8 (using the config file found in the root of the pulp/pulp repo) on the files you modified. Not sure how flake8 works internally, but is it possible that it is skipping those files for some reason?

**Comment by rbarlow** [comment]
On 01/26/2015 10:27 AM, Austin wrote:
> Not sure how flake8 works internally, but is it possible that it is
> skipping those files for some reason?

I don't think so, because I tried running flake8 on exactly one of these
files to see if that would show the issue, and it still passed.

**Comment by barnabycourt** [comment]
ok test

**Comment by asmacdo** [comment]
ok test

**Comment by asmacdo** [comment]
@rbarlow LGTM

**Pull request merged**
