### PR TITLE
added -v and -vv options to admin and consumer clients to get info and d...

### PR DESCRIPTION
**Pull request by skarmark**
Debug level output which was going to the logs before

https://pulp.plan.io/issues/145

The behavior now can be summarized as -
------------------------Normal behavior ---------------------------------------
$ pulp-admin rpm repo create --repo-id test
A resource with the ID "test" already exists.

----------------------- with -v flag ---------------------------------------------
$ pulp-admin -v rpm repo create --repo-id test
2015-03-05 01:34:37,817 - ERROR - Exception occurred:
        href:      /pulp/api/v2/repositories/
        method:    POST
        status:    409
        error:     Duplicate resource: test
        traceback: None
        data:      {u'resource_id': u'test', u'error': {u'code': u'PLP0018', u'data': {u'resource_id': u'test'}, u'description': u'Duplicate resource: test', u'sub_errors': []}}
     
A resource with the ID "test" already exists.

-------------------------- with multiple -v flags ----------------------------------

$ pulp-admin -vv rpm repo create --repo-id test
2015-03-05 01:34:42,109 - DEBUG - sending POST request to /pulp/api/v2/repositories/
2015-03-05 01:34:42,325 - INFO - POST request to /pulp/api/v2/repositories/ with parameters {"display_name": null, "description": null, "distributors": [{"distributor_id": "yum_distributor", "auto_publish": true, "distributor_config": {"http": false, "relative_url": "test", "https": true}, "distributor_type_id": "yum_distributor"}, {"distributor_id": "export_distributor", "auto_publish": false, "distributor_config": {"http": false, "https": true}, "distributor_type_id": "export_distributor"}], "notes": {"_repo-type": "rpm-repo"}, "importer_type_id": "yum_importer", "importer_config": {}, "id": "test"}
2015-03-05 01:34:42,325 - INFO - Response status : 409 

2015-03-05 01:34:42,325 - INFO - Response body :
 {
  "exception": null, 
  "traceback": null, 
  "_href": "/pulp/api/v2/repositories/", 
  "resource_id": "test", 
  "error_message": "Duplicate resource: test", 
  "http_request_method": "POST", 
  "http_status": 409, 
  "error": {
    "code": "PLP0018", 
    "data": {
      "resource_id": "test"
    }, 
    "description": "Duplicate resource: test", 
    "sub_errors": []
  }
}

2015-03-05 01:34:42,325 - ERROR - Exception occurred:
        href:      /pulp/api/v2/repositories/
        method:    POST
        status:    409
        error:     Duplicate resource: test
        traceback: None
        data:      {u'resource_id': u'test', u'error': {u'code': u'PLP0018', u'data': {u'resource_id': u'test'}, u'description': u'Duplicate resource: test', u'sub_errors': []}}
        
A resource with the ID "test" already exists.

### CODE REVIEW

**Comment by ipanova** [comment]
I noticed that there is not difference between situation when you specify -v and do not specify any option during some normal action with no error  - http://fpaste.org/194189/42563635/

**Comment by ipanova** [comment]
In some situation it does not give any useful explanation of failure http://fpaste.org/194193/42563731/
Also notice line 61 and 100. I think at this point it should mention the -vv flag and not -v.
Plus line 103 and 293, I think instead of the information written on line 293 should be displayed the actual error:
"Error downloading metadata
Task Failed 
Importer indicated a failed response"

**Comment by skarmark** [comment]
@ipanova, about your first comment, it is expected. -v gives out INFO level debug messages, so in case of no failures, it can have the same output as without -v flag. 

I am looking into the second comment. It looks like a few referrals to config logging section were not caught by existing unit tests. I will update them.

**Comment by ipanova** [comment]
Great, I have no more comments from my side.
Can someone look into the code itself because i did not check it?

**Comment by beav** [comment]
LGTM

A few lines are >100 char but that can be fixed as part of PEP8 cleanup

**Pull request merged**
