### PR TITLE
Add coverage to runserver

### PR DESCRIPTION
**Pull request by mdellweg**

### CODE REVIEW

**Comment by mdellweg** [comment]
@bmbouter i am quite confident, that this approach has not worked like this the last time i tried.

**Comment by mdellweg** [comment]
ping @pulp/qe

**Comment by bmbouter** [comment]
This looks like it's working to me! @pulp/qe can you lgtm+merge since I'll be out.

@dkliban FYI on this change as well.

**Comment by kersommoura** [comment]
ack.

**Pull request merged**
