### PR TITLE
marking a function as deprecated and changing the places that referenced it

### PR DESCRIPTION
**Pull request by mhrivnak**

### CODE REVIEW

**Comment by ipanova** [comment]
@mhrivnak Since we are deprecating this function, do we still need the tests for it? I think we should also change the reference in tests.

```
$ git grep get_units_across_types
test_unit_association_query.py:        mock_manager.get_units_across_types('repo-1', criteria=criteria)
test_unit_association_query.py:    def test_get_units_across_types(self):
test_unit_association_query.py:        units_1 = self.manager.get_units_across_types('repo-1')
test_unit_association_query.py:        units_2 = self.manager.get_units_across_types('repo-2')
test_unit_association_query.py:        units = self.manager.get_units_across_types('repo-1', criteria)
test_unit_association_query.py:        low_units = self.manager.get_units_across_types('repo-1', low_criteria)
test_unit_association_query.py:        high_units = self.manager.get_units_across_types('repo-1', high_criteria)
test_unit_association_query.py:        skip_units = self.manager.get_units_across_types('repo-1', skip_criteria)
test_unit_association_query.py:        all_units = self.manager.get_units_across_types('repo-1')
test_unit_association_query.py:        after_units = self.manager.get_units_across_types('repo-1', after_criteria)
test_unit_association_query.py:        before_units = self.manager.get_units_across_types('repo-1', before_criteria)
test_unit_association_query.py:        units = self.manager.get_units_across_types('repo-1', criteria)
test_unit_association_query.py:        units = self.manager.get_units_across_types('repo-1', criteria)
```

**Comment by mhrivnak** [comment]
I didn't change the function being tested, so I don't think we necessarily need to change the tests. Once the function actually gets removed, then its tests should obviously be changed or removed.

You've pointed out that the current tests would benefit from some changes, but that is not a new state introduced by this PR.

**Comment by mhrivnak** [comment]
ok test

**Comment by ipanova** [comment]
Agree, LGTM

**Pull request merged**
