### PR TITLE
add update to 'supported-releases.json' to build docs

### PR DESCRIPTION
**Pull request by JayWelborn**
updated build docs as per https://pulp.plan.io/issues/2673?pn=1#change-20902

### CODE REVIEW

**Comment by werwty** [comment]
ok test

**Comment by JayWelborn** [comment]
Awesome! Thanks for letting me hack on pulp!

-Jay

**Comment by werwty** [comment]
Don't forget to add yourself to the Authors file: https://github.com/pulp/pulp/blob/master/AUTHORS

**Comment by JayWelborn** [comment]
added name to authors

**Pull request merged**
