### PR TITLE
Issue #2134 - Removing option from dist config which is not in it

### PR DESCRIPTION
**Pull request by BrnoPCmaniak**
closes #2134
https://pulp.plan.io/issues/2134

### CODE REVIEW

**Comment by asmacdo** [comment]
Nice work! Next time please add a link to the PR when you update redmine to POST.

**Comment by asmacdo** [comment]
We don't enforce commit message rules so consider this a style suggestion, but have a look at this if you have some free time. http://chris.beams.io/posts/git-commit/ 

Thanks to @Ichimonji10 for opening my eyes to the beauty of a good commit message.

**Comment by goosemania** [comment]
@asmacdo , maybe it is better to make a PR against 2.9-dev, what do you think?

**Comment by BrnoPCmaniak** [comment]
@goosemania it was before mentioned to be to 2.9-dev I just realised I forgot to change the branch.

**Comment by BrnoPCmaniak** [comment]
@asmacdo Is it better now?

**Comment by asmacdo** [comment]
@BrnoPCmaniak, yeah that is a great commit message!

**Comment by mhrivnak** [comment]
It looks like the next step here is to rebase on 2.9-dev and submit a new PR to that branch.

**Comment by asmacdo** [comment]
@BrnoPCmaniak Yes, when you have done that (assuming the git goes smoothly,) the LGTM here is still good on the 2.9-dev branch.

**Comment by BrnoPCmaniak** [comment]
Close in favour of https://github.com/pulp/pulp/pull/2709

**Pull request closed without merging**
