### PR TITLE
Updating our test certs to conform to v1 entitlement cert format

### PR DESCRIPTION
**Pull request by daviddavis**
Also, this fixes our tests on F25 which has an updated version of python-rhsm.

fixes #2733
https://pulp.plan.io/issues/2733

### CODE REVIEW

**Comment by bmbouter** [comment]
This looks right. I'm only seeing diff in the certs and I confirmed that the unit tests are passing on F24, F25, and EL7.

**Comment by bmbouter** [comment]
I *think* all the test runners are done, do you know why it says 1 pending of 2 successful checks?

**Comment by daviddavis** [comment]
@bmbouter is master the right branch or should this be against 2.13-dev?

**Comment by bmbouter** [comment]
Ohhhh I didn't look at the branch. 2.13-dev is right and then merge forward. At least for today :)

**Pull request merged**
