### PR TITLE
Fix pulp_resource_mananger typo

### PR DESCRIPTION
**Pull request by daviddavis**
fixes #2726
https://pulp.plan.io/issues/2726

### CODE REVIEW

**Comment by bmbouter** [comment]
ok test

**Comment by bmbouter** [comment]
Actually there were some errors shown in the logs, but they looked like random test failures. I kicked off another run to see if they resolve.

**Comment by bmbouter** [comment]
I'm seeing the same errors on f25 and epel7, so perhaps those images need to be "rebuilt"?

**Comment by dralley** [comment]
ok test

**Comment by dralley** [comment]
@bmbouter the only test failure is due to the test cert / python-rhsm issue ([2733](https://pulp.plan.io/issues/2733))

**Comment by bmbouter** [comment]
Given that the only failure isn't related to this PR, let's merge it.

**Pull request merged**
