### PR TITLE
Move functional tests from pulp-smash into pulp repo

### PR DESCRIPTION
**Pull request by dralley**

### CODE REVIEW

**Comment by dralley** [comment]
Ready for review, but please don't merge yet. Double checking that no more CI changes are needed on the Jenkins side.

**Comment by omaciel** [comment]
@dralley how is this progressing?

**Comment by dralley** [comment]
Since the tests aren't inside the package tree, for this repo, the Pulp 3 PyPI Smasher Jenkins job can't find them in order to run them.

Still working out what the optimal solution to that problem is.

**Comment by omaciel** [comment]
@dralley gotcha. What can we do to help? Would a brainstorm session with QE help?

**Comment by dralley** [comment]
@omaciel After talking with @Ichimonji10 , we think those Pulp 3 Jenkins jobs can just be removed, since they were done before Travis was running smash against every PR.

We would still want Jenkins jobs for testing RHEL7 in particular, but not the way they currently exist.  So for now they can be removed and these PRs can be considered unblocked.

**Comment by omaciel** [comment]
Fantastic! Thank you both @dralley and @Ichimonji10 I would love to see this task done as soon as possible so that we can move forward with our testing plans :) If there is **anything** you need to expedite this issue, please let me know.

**Comment by omaciel** [comment]
cheering_minions

**Pull request merged**
