### PR TITLE
Fix for issue 889.

### PR DESCRIPTION
**Pull request by kaos**
As described here: https://pulp.plan.io/issues/889

### CODE REVIEW

**Comment by beav** [comment]
@kaos can you give more info on how to reproduce this bug? I was not able to get it to happen when publishing a repo.

**Comment by kaos** [comment]
I suspect it may be due to an older version of the pulp server, but that is
just a hunch.

But I think you should be able to see the data that caused this bug in the
server_calls.log.

I'm busy all day today, so I can't help further until tomorrow, at the
earliest.

2015-04-15 22:05 GMT+02:00 Chris Duryee <notifications@github.com>:

**Comment by beav** [comment]
@kaos I wrote a small unit test that tests this patch:

```python
    def test_render_step_missing_details(self):
        """
        Test that no exception is raised when PROGRESS_DETAILS_KEY is missing.
        """
        self.step[reporting_constants.PROGRESS_STATE_KEY] = reporting_constants.STATE_RUNNING
        del self.step[reporting_constants.PROGRESS_DETAILS_KEY]
        self.renderer.render_step(self.step)
```

Can you add this test (or another if you want to write your own) into the `TestPublishStepStatusRenderer` test class and resubmit the PR?

**Comment by beav** [comment]
ok test

**Comment by beav** [comment]
ok test

**Comment by beav** [comment]
@kaos This change looks good and tests pass for it. Many thanks for the patch!

**Comment by kaos** [comment]
Thank you for accepting it :)
 Den 30 apr 2015 20:23 skrev "Chris Duryee" <notifications@github.com>:

**Pull request merged**
