### PR TITLE
Fix pulp-admin error when not running in tty

### PR DESCRIPTION
**Pull request by Poil**
fixes #4068
https://pulp.plan.io/issues/4068

### CODE REVIEW

**Comment by dralley** [comment]
ok test

**Comment by dralley** [comment]
ok test

**Comment by dralley** [comment]
@Poil Thank you!

**Comment by dralley** [comment]
@Poil Judging by the email hitting my inbox, I assume RCM Pulp is having issues with those merge commits I made to bring it up to date?

**Comment by Poil** [comment]
Hi,

Sorry for the delay, what is the problem ?

**Comment by dralley** [comment]
Nothing I was just getting a bunch of emails from bugzilla, but I assume it's worked out now :)

**Pull request merged**
