### PR TITLE
Modify exception type in importer_config

### PR DESCRIPTION
**Pull request by Akasurde**
Fixes https://pulp.plan.io/issues/921

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

### CODE REVIEW

**Comment by bmbouter** [comment]
ok test

**Comment by Akasurde** [comment]
Can you anyone look into build failure and let me know ? I don't have permission to [default](https://pulp-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/unittest-pulp-pr/616/)

**Comment by dralley** [comment]
ok test

**Comment by dralley** [comment]
@Akasurde Have you tried running the unit tests locally?  If you have a vagrant environment set up, use

```ptests &> test_results.txt```

**Comment by Akasurde** [comment]
@dralley Yes. I have tried running the unit tests locally using `psmash`. I will do `ptests` again.

**Comment by bmbouter** [comment]
@Akasurde Thank you for the PR. Sorry the Jenkins results aren't public. We really want to fix that, but I'm not exactly sure what to do.

Regarding tests, the `psmash` runs the integration tests, and `ptests` (or maybe `ptest`) run the unit tests. These PR builders run the unit tests and only show green when the unit tests are passing on all distributions. The integration tests are run nightly through Jenkins jobs that are also not publicly visible. It's great that you are running those locally too; thank you for that.

**Comment by Akasurde** [comment]
@bmbouter OK. I will do the unit testing at my end and will update once, it is done.

**Comment by dralley** [comment]
ok test

**Comment by dralley** [comment]
@Akasurde FYI, the Jenkins PR test results are public now thanks to some great work by @dkliban

**Comment by ipanova** [comment]
ok test

**Comment by ipanova** [comment]
@Akasurde any progress on this?

**Comment by dralley** [comment]
@Akasurde ping

**Comment by dralley** [comment]
ok test

**Comment by dralley** [comment]
@Akasurde , we are closing this PR for now, but if you have time to fix it up, feel free to reopen a new PR

**Pull request closed without merging**
