### PR TITLE
Align default settings with new content app

### PR DESCRIPTION
**Pull request by mdellweg**
https://pulp.plan.io/issues/4239
re #4239

### CODE REVIEW

**Comment by mdellweg** [comment]
You could have asked me to delete it. ;)

**Comment by mdellweg** [comment]
@bmbouter You might also need to re'MODIFIED' the plan.io ticket.

**Comment by bmbouter** [comment]
@mdellweg I moved the ticket back to MODIFIED. I do think that we need to delete this file every since we switched to dynaconf. I'll email pulp-dev because I want to highlight the reasoning there.

**Comment by bmbouter** [comment]
I wrote it up here:  https://www.redhat.com/archives/pulp-dev/2018-December/msg00065.html

**Pull request merged**
