### PR TITLE
If repository hasn't been published before, publish without fast-foward

### PR DESCRIPTION
**Pull request by negillett**
Commandeering #3967 from @midnightercz 

Closes #5659

### CODE REVIEW

**Comment by nathanegillett** [comment]
ok test

**Comment by ipanova** [comment]
ok test

**Comment by negillett** [comment]
Hey, @ipanova. Any chance we can get someone to have a look at this for us?

**Review by midnightercz — APPROVED** [review]

**Comment by negillett** [comment]
@ipanova @dkliban, anyone able to review this?

**Review by ipanova — APPROVED** [review]

**Comment by negillett** [comment]
Thanks, @ipanova!

**Pull request merged**
