### PR TITLE
Add unit querying & association support required for plugin conversio…

### PR DESCRIPTION
**Pull request by barnabycourt**
…n to mongoengine

https://pulp.plan.io/issues/862

### CODE REVIEW

**Comment by barnabycourt** [comment]
*Note, this PR exists for checking with the PR builder but I am still cleaning up the comments & code

**Comment by ipanova** [comment]
@barnabycourt  I think you provided wrong number of issue to this PR

**Comment by barnabycourt** [comment]
@ipanova you are absolutely correct, copy and paste fail, I have updated the comment

**Comment by barnabycourt** [comment]
Closed in favor of https://github.com/pulp/pulp/pull/1912 so we are targeting 2.8 with the changes

**Pull request closed without merging**
