### PR TITLE
Add tmux to the development environment.

### PR DESCRIPTION
**Pull request by rbarlow**

### CODE REVIEW

**Comment by jeremycline** [comment]
I'm holding this review hostage until you merge some of the other dev environment-related PRs you've got open.

**Comment by rbarlow** [comment]
Jeremy Cline wrote:
> I'm holding this review hostage until you merge some of the other dev
> environment-related PRs you've got open.

lololol

Well I'm doing like 2.5 FTE's worth of work right now so I won't be able
to get to them until much later, especially since my dev environment is
so fragile with all the 2.6 stuff I've got to do ☹

-- 
Randy Barlow
irc:   bowlofeggs

**Comment by jeremycline** [comment]
It sounds like you've got... tmux to do.

**Comment by rbarlow** [comment]
Jeremy Cline wrote:
> It sounds like you've got... tmux to do.

@jcline, ladies and gentlemen!

**Pull request merged**
