### PR TITLE
BZ1193689 - Removed getting of working directories where they are not used

### PR DESCRIPTION
**Pull request by dkliban**
https://bugzilla.redhat.com/show_bug.cgi?id=1193689

### CODE REVIEW

**Comment by asmacdo** [comment]
LGTM

**Comment by dkliban** [comment]
ok test

**Comment by asmacdo** [comment]
@dkliban, the name of this PR should be changed.

Do you have a way to confirm that the working directory is not being used in each of these cases?

**Comment by asmacdo** [comment]
Since these are not allowed anyway, I think we are good to merge this. LGTM

**Comment by dkliban** [comment]
ok test

**Pull request merged**
