### PR TITLE
Require Ansible 2.3.2+

### PR DESCRIPTION
**Pull request by Ichimonji10**
Also, fix numbering in ordered list.

See: https://github.com/pulp/devel/pull/95

### CODE REVIEW

**Comment by dralley** [comment]
I found a problem ex post facto

Without the line ```sudo pip3 install virtualenv```, I get the following error:

```TASK [pulp3 : Install pulpcore] *******************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to find required executable virtualenv in paths: /sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin"}
```

**Comment by ammaritiz** [comment]
Yes, I found this problem too while working on the packer template. I had
to add a step to install virtualenv.

Thanks,
Ammar

On Oct 7, 2017 8:50 PM, "Daniel Alley" <notifications@github.com> wrote:

I found a problem ex post facto

Without the line sudo pip3 install virtualenv, I get the following error:

fatal: [localhost]: FAILED! => {"changed": false, "failed": true,
"msg": "Failed to find required executable virtualenv in paths:
/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin"}

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/pulp/pulp/pull/3169#issuecomment-334975357>, or mute
the thread

**Comment by Ichimonji10** [comment]
@ammaritiz @dkliban The whole point of this series of PRs is that the virtualenv executable and package *aren't* required. See https://github.com/pulp/ansible-pulp3/pull/4

**Comment by dralley** [comment]
@Ichimonji10 I hadn't seen that PR (and it isn't linked) but I will test it today and get it merged.

**Comment by Ichimonji10** [comment]
I should've linked to it.

**Pull request merged**
